# Generated by Django 5.1.2 on 2026-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_client_management',
            field=models.BooleanField(default=False, verbose_name='Client Management'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_dispatch',
            field=models.BooleanField(default=False, verbose_name='Dispatch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_leads',
            field=models.BooleanField(default=False, verbose_name='Leads'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_petty_cash',
            field=models.BooleanField(default=False, verbose_name='Petty Cash'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_production',
            field=models.BooleanField(default=False, verbose_name='Production'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_stock_items',
            field=models.BooleanField(default=False, verbose_name='Stock Items'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_vendor_management',
            field=models.BooleanField(default=False, verbose_name='Vendor Management'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Super Admin has access to every module regardless of individual permissions.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accounts', 'Accounts'), ('factory', 'Factory'), ('accountant', 'Accountant'), ('office', 'Office')], max_length=10),
        ),
    ]
