# Generated by Django 5.1.2 on 2026-07-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0029_applicationarea_leadsubdepartment_and_more'),
        ('UserDetail', '0003_user_can_client_management_user_can_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_sub_department',
            field=models.ForeignKey(blank=True, help_text='Sub-department this user belongs to for the Leads module (Sales / can_leads users only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='Operations.leadsubdepartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accounts', 'Accounts'), ('factory', 'Factory'), ('accountant', 'Accountant'), ('office', 'Office'), ('sales', 'Sales')], max_length=10),
        ),
    ]
