# Generated by Django 5.1.2 on 2026-10-08 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hierarchy level (1 = top). Users with a higher level number are below this user.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
