# Generated by Django 5.1.3 on 2026-10-08 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserDetail", "0005_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Hierarchy level (1 = top). Users with a higher level number are below this user.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct supervisor (must have a lower level number). Leave empty to be visible to all upper levels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
