# Generated by Django 5.1.2 on 2026-10-08 13:38

import UserDetail.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0006_user_level_user_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_hr',
            field=models.BooleanField(default=False, verbose_name='HR'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accounts', 'Accounts'), ('factory', 'Factory'), ('accountant', 'Accountant'), ('office', 'Office'), ('sales', 'Sales'), ('hr', 'HR')], max_length=10),
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('personal_mobile', models.CharField(blank=True, max_length=15)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('aadhar_file', models.FileField(blank=True, help_text='Aadhar card (PDF/Image)', null=True, upload_to=UserDetail.models.employee_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), UserDetail.models.validate_document_size])),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_file', models.FileField(blank=True, help_text='PAN card (PDF/Image)', null=True, upload_to=UserDetail.models.employee_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), UserDetail.models.validate_document_size])),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_no', models.CharField(blank=True, max_length=30)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('bank_proof_file', models.FileField(blank=True, help_text='Cancelled cheque / passbook (PDF/Image)', null=True, upload_to=UserDetail.models.employee_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), UserDetail.models.validate_document_size])),
                ('photo', models.FileField(blank=True, help_text='Employee photo (PDF/Image)', null=True, upload_to=UserDetail.models.employee_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), UserDetail.models.validate_document_size])),
                ('office_mobile', models.CharField(blank=True, max_length=15)),
                ('device_details', models.CharField(blank=True, help_text='Office mobile make / model', max_length=255)),
                ('imei_1', models.CharField(blank=True, max_length=20)),
                ('imei_2', models.CharField(blank=True, max_length=20)),
                ('sim_card_in_name_of', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='UserDetail.employeedetail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned / Paid'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='casual', max_length=10)),
                ('day_type', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=4)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
