# Generated by Django 5.1.2 on 2026-04-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatch',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='productionconsumption',
            name='batch',
        ),
        migrations.CreateModel(
            name='ProductionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_code', models.CharField(max_length=20, unique=True)),
                ('production_date', models.DateField()),
                ('total_output_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='Operations.productioncard'),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='production_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='Operations.productioncard'),
        ),
    ]
