# Generated by Django 5.1.2 on 2026-04-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_remove_productionbatch_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncard',
            name='accounted',
            field=models.BooleanField(default=False),
        ),
    ]
