# Generated by Django 5.1.2 on 2026-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0004_clientaddress_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
