# Generated by Django 5.1.2 on 2026-04-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0005_alter_dispatch_dispatch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='unit',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='e.g., Truck, Van, Bike', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_code',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Operations.dispatch')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Operations.stockitem')),
            ],
        ),
    ]
