# Generated by Django 5.1.2 on 2026-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0006_remove_dispatch_quantity_remove_dispatch_stock_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='accounted',
            field=models.BooleanField(default=False, help_text='Mark as accounted in books'),
        ),
    ]
