# Generated by Django 5.1.2 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0007_dispatch_accounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
