# Generated by Django 5.1.2 on 2026-04-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0009_dispatchitem_is_active_pettycash_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('office', 'Office'), ('factory', 'Factory')], max_length=20, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pettycash',
            name='is_active',
        ),
        migrations.AddField(
            model_name='expensehead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-04-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pettycash',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='expense_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='Operations.expensehead'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Operations.pettycashaccount'),
        ),
    ]
