# Generated by Django 5.1.2 on 2026-04-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0010_pettycashaccount_remove_pettycash_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='expense_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='Operations.expensehead'),
        ),
    ]
