# Generated by Django 5.1.2 on 2026-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0011_alter_pettycash_expense_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncard',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productioncard',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productioncard',
            name='total_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productioncard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
