# Generated by Django 5.1.2 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0013_vendorprofile_vendorinward_stockinward_inward_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
