# Generated by Django 5.1.2 on 2026-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0014_alter_stockitem_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='gst',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
