# Generated by Django 5.1.2 on 2026-04-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0015_stockitem_gst_stockitem_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
