# Generated by Django 5.1.2 on 2026-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0017_stocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number for accounting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pdf',
            field=models.FileField(blank=True, help_text='Invoice/Dispatch PDF', null=True, upload_to='dispatch_pdfs/'),
        ),
        migrations.AddField(
            model_name='vendorinward',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number for accounting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorinward',
            name='pdf',
            field=models.FileField(blank=True, help_text='Invoice/Inward PDF', null=True, upload_to='inward_pdfs/'),
        ),
    ]
