# Generated by Django 5.1.2 on 2026-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0018_dispatch_invoice_number_dispatch_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinward',
            name='image',
            field=models.ImageField(blank=True, help_text='Inward receipt/proof image', null=True, upload_to='inward_images/'),
        ),
    ]
