# Generated by Django 5.1.2 on 2026-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0019_vendorinward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Pieces'), ('BAGS', 'BAGS'), ('NOS', 'NOS'), ('GRAMS', 'GRAMS'), ('KGS', 'KGS'), ('PACK', 'PACK'), ('ROLL', 'ROLL'), ('SQ FT', 'SQ FT')], max_length=10),
        ),
    ]
