# Generated by Django 5.1.2 on 2026-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0020_alter_stockitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncard',
            name='production_incharge',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
