# Generated by Django 5.1.2 on 2026-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0021_productioncard_production_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='paid_by',
            field=models.CharField(blank=True, help_text='Person who made payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='paid_via',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='particulars',
            field=models.TextField(blank=True, help_text='Details other than remarks', null=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('advance', 'Advance'), ('part', 'Part'), ('final', 'Final')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='to',
            field=models.CharField(blank=True, help_text='Direct recipient name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Pieces'), ('BAGS', 'BAGS'), ('NOS', 'NOS'), ('GRAMS', 'GRAMS'), ('KGS', 'KGS'), ('PACK', 'PACK'), ('ROLL', 'ROLL'), ('SQ FT', 'SQ FT'), ('SQ MTR', 'SQ MTR'), ('CBM', 'CBM')], max_length=10),
        ),
    ]
