# Generated by Django 5.1.2 on 2026-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0023_pettycashlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinward',
            name='invoice_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
