# Generated by Django 5.1.2 on 2026-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0025_alter_clientaddress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag - False means deleted'),
        ),
    ]
