# Generated by Django 5.1.2 on 2026-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0026_pettycash_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
