# Generated by Django 5.1.2 on 2026-06-28 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0027_alter_dispatch_dispatch_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('date_of_connect', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=255)),
                ('party_type', models.CharField(choices=[('dealer', 'Dealer'), ('distributor', 'Distributor'), ('waterproofing_applicator', 'Waterproofing Applicator'), ('tile_adhesive_applicator', 'Tile Adhesive Applicator'), ('oem', 'OEM'), ('architect', 'Architect'), ('interior_designer', 'Interior Designer'), ('pmc', 'PMC'), ('builder_project', 'Builder Project'), ('individual_project', 'Individual Project'), ('bungalow', 'Bungalow'), ('structural_consultant', 'Structural Consultant'), ('mepf_consultant', 'MEPF Consultant'), ('other', 'Other')], max_length=50)),
                ('party_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lead_status', models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('details_shared', 'Details Shared'), ('appointment_fixed', 'Appointment Fixed'), ('visit_done', 'Visit Done'), ('proposal_sent', 'Proposal Sent'), ('sample_to_be_done', 'Sample To Be Done'), ('sample_done', 'Sample Done'), ('negotiation_followup', 'Negotiation / Follow-up'), ('won', 'Won'), ('repeat_order', 'Repeat Order'), ('closed_lost', 'Closed – Lost'), ('closed_forwarded', 'Closed – Forwarded'), ('on_hold', 'On Hold'), ('future_potential', 'Future Potential'), ('other', 'Other')], default='new_lead', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Remarks / Briefing about the lead')),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('briefing', models.TextField(help_text='What was discussed in this call')),
                ('lead_status', models.CharField(blank=True, choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('details_shared', 'Details Shared'), ('appointment_fixed', 'Appointment Fixed'), ('visit_done', 'Visit Done'), ('proposal_sent', 'Proposal Sent'), ('sample_to_be_done', 'Sample To Be Done'), ('sample_done', 'Sample Done'), ('negotiation_followup', 'Negotiation / Follow-up'), ('won', 'Won'), ('repeat_order', 'Repeat Order'), ('closed_lost', 'Closed – Lost'), ('closed_forwarded', 'Closed – Forwarded'), ('on_hold', 'On Hold'), ('future_potential', 'Future Potential'), ('other', 'Other')], help_text='Lead status after this call', max_length=50)),
                ('next_followup', models.DateTimeField(blank=True, help_text='Next follow-up date & time after this call', null=True)),
                ('follow_up_done', models.BooleanField(default=False, help_text='Mark as True when the follow-up is completed')),
                ('forwarded_to', models.CharField(blank=True, help_text='Email/name of person forwarded to (when status = Closed-Forwarded)', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='Operations.lead')),
            ],
            options={
                'ordering': ['-call_date', '-created_at'],
            },
        ),
    ]
