# Generated by Django 5.1.2 on 2026-07-25 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0028_lead_leadcallrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadSubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. OEM / RC / APP', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSystemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_products', to='Operations.applicationarea')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('application_area', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_leads', to='Operations.applicationarea')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_detail', to='Operations.lead')),
                ('selected_system_products', models.ManyToManyField(blank=True, related_name='app_leads', to='Operations.applicationsystemproduct')),
            ],
        ),
        migrations.AddField(
            model_name='applicationarea',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_areas', to='Operations.leadsubdepartment'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_department',
            field=models.ForeignKey(blank=True, help_text='Leads sub-department (OEM / RC / Applications / …)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='Operations.leadsubdepartment'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('quotation_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='Operations.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('sr_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial_sent', 'Partial Sent'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sent_to_factory_at', models.DateTimeField(blank=True, null=True)),
                ('factory_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_requisites', to='Operations.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubDeptStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default rate; can be overridden in quotation', max_digits=12, null=True)),
                ('uom', models.CharField(choices=[('NOS', 'NOS'), ('KGS', 'KGS'), ('BAGS', 'BAGS'), ('GRAMS', 'GRAMS'), ('PACK', 'PACK'), ('ROLL', 'ROLL'), ('SQ FT', 'SQ FT'), ('SQ MTR', 'SQ MTR'), ('CBM', 'CBM'), ('LTR', 'LTR'), ('ML', 'ML'), ('PCS', 'PCS'), ('MTR', 'MTR')], default='NOS', max_length=20, verbose_name='Unit of Measurement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='Operations.leadsubdepartment')),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('sub_department', 'product_name')},
            },
        ),
        migrations.CreateModel(
            name='SampleRequisiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('qty_sent', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity actually sent by factory', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sample_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Operations.samplerequisite')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sr_items', to='Operations.subdeptstockitem')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(blank=True, help_text='Copied from item but can be overridden', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional line-level description')),
                ('is_active', models.BooleanField(default=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Operations.quotation')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='Operations.subdeptstockitem')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSystemProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Used when stock_item is not linked', max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('system_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Operations.applicationsystemproduct')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_product_items', to='Operations.subdeptstockitem')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFixedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('application_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_items', to='Operations.applicationarea')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_items', to='Operations.subdeptstockitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicationarea',
            unique_together={('sub_department', 'name')},
        ),
    ]
