# Generated by Django 5.1.2 on 2026-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0029_applicationarea_leadsubdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdeptstockitem',
            name='warranty',
            field=models.CharField(blank=True, help_text="Optional warranty info, e.g. '1 Year', '6 Months'", max_length=100, null=True),
        ),
    ]
