# Generated by Django 5.1.2 on 2026-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0030_subdeptstockitem_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdeptstockitem',
            name='uom',
            field=models.CharField(default='NOS', max_length=20, verbose_name='Unit of Measurement'),
        ),
    ]
