# Generated by Django 5.1.2 on 2026-07-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0031_alter_subdeptstockitem_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Used when stock_item is not linked', max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='warranty',
            field=models.CharField(blank=True, help_text="Warranty info, e.g. '1 Year'", max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='Operations.subdeptstockitem'),
        ),
    ]
