# Generated by Django 5.1.2 on 2026-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0033_quotationitem_application_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='scope',
            field=models.CharField(blank=True, default='', help_text="Scope of work, e.g. 'LABOUR + MATERIAL', 'LABOUR ONLY'", max_length=100),
        ),
    ]
