# Generated by Django 5.1.2 on 2026-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0034_quotationitem_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='application_area',
            field=models.CharField(blank=True, help_text='Optional application area for this item', max_length=100, null=True),
        ),
    ]
