# Generated by Django 5.1.2 on 2026-10-08 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0036_lead_city_lead_country_lead_pincode_lead_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Users who share this lead with the owner and can update / follow it up.', related_name='leads_collaborating', to=settings.AUTH_USER_MODEL),
        ),
    ]
