# Generated by Django 5.1.2 on 2026-10-10 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0037_lead_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=255)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(default='PASSES', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='Operations.stockitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
